# Generated by Django 5.0.1 on 2024-01-26 02:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0005_order_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="deliver_address",
            new_name="delivery_address",
        ),
    ]
