# Generated by Django 5.0.1 on 2024-01-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0007_order_products"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(related_name="orders", to="shopapp.product"),
        ),
    ]
