# Generated by Django 5.0.1 on 2024-01-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0008_alter_product_options_alter_order_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reciept",
            field=models.FileField(null=True, upload_to="orders/receipts/"),
        ),
    ]
