# Generated by Django 5.0.1 on 2024-01-29 05:57

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopapp", "0009_order_reciept"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shopapp.models.gen_product_preview_directory_name,
            ),
        ),
    ]
